### ISSUE TITLE
[Bug] My title闪退

### ISSUE THREAD

**Issue by IR141** [Clean-Reader/CleanReader.Desktop#28]
### Bug description / Bug 描述

1.闪退
2.发现书籍不能用

### Reproduce steps / 复现问题的步骤

```plain text
1.添加书籍后 打开书籍就闪退
2.发现书籍不能用
```

### Expected behavior / 预期行为

期待.jpg

### Screenshot / 截图

![uTools_1650263175819](https://user-images.githubusercontent.com/65697496/163765286-8d35cb35-a03b-472f-baf5-90ef0686528b.png)
![uTools_1650263234642](https://user-images.githubusercontent.com/65697496/163765297-1e5f0ff4-2a12-4c85-aa0c-da183960a005.png)

### Application source / 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] Others / 其它

### System version

- [X] Windows 11 21H2 (Build 22000)
- [ ] Others / 其它

### Device / 运行设备

Desktop/桌面/台式机

**Comment by Richasy** [comment]
与 #29 合并
