### ISSUE TITLE
[Bug] 打开书籍闪退等

### ISSUE THREAD

**Issue by IR141** [Clean-Reader/CleanReader.Desktop#29]
### Bug description / Bug 描述

1.闪退
2.发现书籍不能用

### Reproduce steps / 复现问题的步骤

```plain text
1.打开书籍闪退
2.如图
```

### Expected behavior / 预期行为

期待.jpg

### Screenshot / 截图

![uTools_1650263175819](https://user-images.githubusercontent.com/65697496/163765432-3a3c81d4-8c21-4d24-bfc4-4d9a006b4f40.png)
![uTools_1650263234642](https://user-images.githubusercontent.com/65697496/163765436-cb524c80-8ec6-4acb-8ba5-88e990b555aa.png)

### Application source / 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] Others / 其它

### System version

- [X] Windows 11 21H2 (Build 22000)
- [ ] Others / 其它

### Device / 运行设备

Desktop/桌面/台式机

**Comment by Richasy** [comment]
可以试下新的版本  [四月更新 - 4](https://github.com/Clean-Reader/CleanReader.Desktop/releases/tag/v3.2204.11.0)

**Comment by IR141** [comment]
可以了 谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Clean-Reader/CleanReader.Desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Clean-Reader/CleanReader.Desktop] [Bug] 打开书籍闪退等 (Issue #29)





 
可以试下新的版本  四月更新 - 4
