### ISSUE TITLE
[Bug] 版本3.2204.10.0中epub文献注释无法正确跳转

### ISSUE THREAD

**Issue by Curious-r** [Clean-Reader/CleanReader.Desktop#30]
### Bug description / Bug 描述

点击epub文献中的注释标记无法正确跳转至相应注释页，点击注释页的序号无法正确跳转到相应原文界面。
此问题疑似为版本3.2204.10.0新增，本版本上线前有正常使用注释跳转功能的印象。
值得注意的细节，在点击注释序号的时候，阅读工具栏会出乎意料的闪现并消失。

### Reproduce steps / 复现问题的步骤

```plain text
1.打开应用
2.点击《万历十五年》
3.翻动页面找到任何一个注释标记并点击
4.观察是否正确跳转至对应的注释页
5.翻动至任意注释页面，点击任意注释条目序号
6.观察是否正确跳转至对应的注释页
7.观察未正确跳转的情况下是否有阅读工具栏闪现
```

### Expected behavior / 预期行为

点击注释标记正确跳转至相应的注释页面，点击注释页面的序号正确的跳转回相应原文页面。

### Screenshot / 截图

![image](https://user-images.githubusercontent.com/19733878/163788550-e14360d2-357e-45cb-a097-e07da6722c32.png)

### Application source / 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] Others / 其它

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [X] Others / 其它

### Other system versions / 其它系统版本

dev 22598

### Device / 运行设备

Tablet/平板或笔记本

**Comment by Curious-r** [comment]
补充：重装了应用之后，似乎只有第一次点击跳转是正常的

**Comment by luminosara** [comment]
> 补充：重装了应用之后，似乎只有第一次点击跳转是正常的

同样是遇到了这个问题，有的时候工具栏会抖动，有的时候页面会左右抖动，长章节复现似乎较为容易，一般只有前几个注释能正常跳转，后面的均不行。

出现这个问题后似乎在一个章节的开头向前翻页也会遇到错误，并不是上一章节的最尾端。

顺带问一下，能不能像第二版一样点击注释会跳出一个小窗口，对于一些并不是很重要的注释可以减少阅读时跳来跳去的打断

多谢开发者大大！
