### ISSUE TITLE
有考虑适配win10版本的想法吗？

### ISSUE THREAD

**Issue by youlan2333** [Clean-Reader/CleanReader.Desktop#35]
### Description / 问题描述

本人win10系统，感觉现在win11系统并没有宣传中的好用，大部分人还是用win10比较多一点吧？

### Solution / 描述解决方案

作者有考虑适配win10版本的想法吗？

**Comment by Richasy** [comment]
使用 Windows App SDK 开发的应用基本都只支持 Win11 桌面环境，换句话说，如果微软解决 WAS 在 Win10 上的问题，我这边才能跟进，目前来说，无法支持 Win10

**Comment by WilliamK7** [comment]
请问一下作者有win10可用的备份吗？
在电脑上看小说一直在用这个软件，现在要换电脑了，希望能继续有这样的高质量体验
谢谢
