### ISSUE TITLE
[Bug] 导入epub时闪退

### ISSUE THREAD

**Issue by 6xingyv** [Clean-Reader/CleanReader.Desktop#37]
### Bug description / Bug 描述

在导入epub时，发生了闪退。
导入方式为直接点击epub打开干净阅读和 与 在干净阅读内点击“添加书籍”后选择对应本地文件。

### Reproduce steps / 复现问题的步骤

```plain text
1.打开应用
2.点击"导入书籍"
3.点击“本地导入”
4.选择本地文件导入
5.转圈加载后崩溃
```

### Expected behavior / 预期行为

成功导入

### Application source / 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] Others / 其它

### System version

- [X] Windows 11 21H2 (Build 22000)
- [ ] Others / 其它

### Device / 运行设备

Desktop/桌面/台式机

### Remark / 备注

附上导入的文件
[Education Free and Compulsory](https://cdn.mises.org/Education%20Free%20and%20Compulsory_3.epub)

**Comment by Richasy** [comment]
在我的设备上不能复现这个问题
