### ISSUE TITLE
[Feature] 阅读时深色主题支持

### ISSUE THREAD

**Issue by RayGicEFL** [Clean-Reader/CleanReader.Desktop#39]
### Description / 问题描述

在晚上所以软件都是深色主题的时候，打开一本书背景是白色的直接亮瞎……

### Solution / 描述解决方案

希望可以直接把书的内容显示在应用背景（如灰色或者云母）之上，这样神色主题时背景自然是暗的，如果以后winui3 desktop支持云母那会更好看

**Comment by Richasy** [comment]
关于这个，阅读背景和文本颜色都是可调的（除非你所阅读的epub限制死了背景色和前景色），你可以在 [界面设置](https://docs.richasy.cn/clean-reader/desktop#%E7%95%8C%E9%9D%A2%E8%AE%BE%E7%BD%AE) 中调整
