### ISSUE TITLE
[Feature] 导入本地书籍目录正则不完善导致章节无法准确识别

### ISSUE THREAD

**Issue by GitHubXieYihang** [Clean-Reader/CleanReader.Desktop#48]
### Description / 问题描述

导入本地书籍目录正则不完善导致章节无法准确识别

### Solution / 描述解决方案

在程序中内置几款目录正则，就像阅读那样，我在遇到这个问题之后把手机上的阅读里面的目录正则搬过来就可以正确识别了，所以我希望干净阅读这个软件也可以像阅读那样内置多种目录正则，比如：
^[ 　\t]{0,4}(?:序章|序言|卷首语|扉页|楔子|正文(?!完|结)|终章|后记|尾声|番外|第?\s{0,4}[\d〇零一二两三四五六七八九十百千万壹贰叁肆伍陆柒捌玖拾佰仟]+?\s{0,4}(?:章|节(?!课)|卷|集(?![合和])|部(?![分赛游])|篇(?!张))).{0,30}$

**Comment by RainbowYang** [comment]
另外，也没有过滤目录中的”第一章“，导致会与正文中的”第一章“重复。
![image](https://user-images.githubusercontent.com/20553594/189927938-fa50514d-94d6-43a1-8a47-01c17c00c1ad.png)

**Comment by GitHubXieYihang** [comment]
> 另外，也没有过滤目录中的”第一章“，导致会与正文中的”第一章“重复。 ![image](https://user-images.githubusercontent.com/20553594/189927938-fa50514d-94d6-43a1-8a47-01c17c00c1ad.png)

我这只是其中一个正则而已，阅读里面还有很多正则，你可以去看看
