### ISSUE TITLE
[Feature] 期待支持Calibre或OPDS的书源

### ISSUE THREAD

**Issue by mwnu** [Clean-Reader/CleanReader.Desktop#60]
### Description / 问题描述

Windows上最简洁的阅读应用，值得付费。
非小说爱好者，个人的书库放在自建的calibre-web服务器上，网上也有很多公开的书库。
Calibre支持OPDS（Open Publication Distribution System 开放式出版发布系统，一种电子书在线目录公开标准）方式订阅，使得第三方应用可以连接calibre书库作为书源。

### Solution / 描述解决方案

期待这款软件也加入这种标准。

**Comment by copurxia** [comment]
蹲
