### ISSUE TITLE
迷你模式下软件是置顶模式，希望可以修改

### ISSUE THREAD

**Issue by yaoshuangshl** [Clean-Reader/CleanReader.Desktop#64]
### Bug description / Bug 描述

迷你模式下软件是置顶模式，希望可以修改

### Reproduce steps / 复现问题的步骤

```plain text
1.打开应用
2.打开书籍
3.设置为迷你模式
4.迷你模式下书籍置顶显示
```

### Expected behavior / 预期行为

修改为正常模式，或者增加相应置顶选项按钮。

### Application source / 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] Others / 其它

### System version

- [X] Windows 11 21H2 (Build 22000)
- [ ] Others / 其它

### Device / 运行设备

Tablet/平板或笔记本

### We are the world / 人人为我，我为人人

None

**Comment by Richasy** [comment]
迷你就是小窗模式，而小窗本就是置顶，这个是应用框架的行为，暂时不会修改
