### ISSUE TITLE
[Bug] epub文件翻过一些页后，书页显示不正常（初步测试关闭平滑滚动可以修复）

### ISSUE THREAD

**Issue by Curious-r** [Clean-Reader/CleanReader.Desktop#8]
### Bug description / Bug 描述

在干净阅读（winUI3）中导入本地epub书籍阅读时，看了几页之后，书页显示就会不正常，具体表现类似页面位置偏移。关闭平滑滚动功能之后恢复正常。

### Reproduce steps / 复现问题的步骤

```plain text
1.打开应用
2.点击《万历十五年》
3.确认“界面”设置中开启了平滑滚动
4.使用鼠标滚轮向后连续翻页
```

### Expected behavior / 预期行为

页面上正常显示本页内容，如图。

### Screenshot / 截图

正常状态截图：
![image](https://user-images.githubusercontent.com/19733878/162656335-06213260-450f-4462-85f6-2cc2878f4219.png)

异常截图：
![image](https://user-images.githubusercontent.com/19733878/162655786-195ad0ff-6dff-40fc-b155-e985dd90038a.png)

### Application source / 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] Others / 其它

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [X] Others / 其它

### Other system versions / 其它系统版本

WIndows 11 insder previem 22593.1

### Device / 运行设备

Tablet/平板或笔记本

### Remark / 备注

感谢开发者的付出

**Comment by Curious-r** [comment]
另附测试的epub文件：
[万历十五年（经典版） by 黄仁宇 [黄仁宇] (z-lib.org).zip](https://github.com/Clean-Reader/CleanReader.Desktop/files/8460676/by.z-lib.org.zip)

**Comment by luminosara** [comment]
遇到了同样的问题，滚轮连续翻页后触发
